branches:
  only:
    - master
language: node_js
node_js:
- lts/*
git:
  depth: 3
install:
- yarn global add @lhci/cli
script:
- lhci autorun --upload.target=temporary-public-storage --collect.staticDistDir=./ --url=http://localhost/static
addons:
  chrome: stable
cache: yarn
